#!/bin/bash

secret_filename="$HOME/.shell/login_secret"
script_home=$(dirname $(realpath "$0"))
source_dir=$(realpath "$script_home/../include")
if [[ "$1" != "" ]]; then
    source_dir=$1
fi

echo "Coping dotfiles from $source_dir to $HOME"

cp -R $source_dir/.bash $HOME/
cp -R $source_dir/.sh $HOME/
cp -R $source_dir/.shell $HOME/
cp -R $source_dir/.zsh $HOME/
cp $source_dir/.bash_logout $HOME/
cp $source_dir/.bash_profile $HOME/
cp $source_dir/.bashrc $HOME/
cp $source_dir/.profile $HOME/
cp $source_dir/.zshenv $HOME/
cp $source_dir/.zprofile $HOME/
cp $source_dir/.zshrc $HOME/

echo "dotfiles copied"

fill_login_secret() {
    echo "Curling contents of url '$1' and appending it to '$secret_filename'"
    curl -fsL -w '\n' "$1" >> $secret_filename
}

filename="$HOME/.secret_links"
if [ -r "$filename" ]; then
    echo "Found secret links file"
    echo "Cleaning $secret_filename"
    rm $secret_filename || :
    touch $secret_filename
    regex='(https?|ftp|file)://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
    while read line; do
        if [[ $line =~ $regex ]]
        then 
            echo "Valid link: $line"
            fill_login_secret $line
        else
            echo "Invalid link: $line"
        fi
    done <$filename
fi
