#!/bin/bash

secret_filename="$HOME/.shell/login_secret"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SOURCE_DIR=$(realpath "$DIR/../include")
if [[ "$1" != "" ]]; then
    SOURCE_DIR=$1
fi

echo "Coping dotfiles from $SOURCE_DIR to $HOME"

cp -R $SOURCE_DIR/.bash $HOME/
cp -R $SOURCE_DIR/.sh $HOME/
cp -R $SOURCE_DIR/.shell $HOME/
cp -R $SOURCE_DIR/.zsh $HOME/
cp $SOURCE_DIR/.bash_logout $HOME/
cp $SOURCE_DIR/.bash_profile $HOME/
cp $SOURCE_DIR/.bashrc $HOME/
cp $SOURCE_DIR/.profile $HOME/
cp $SOURCE_DIR/.zshenv $HOME/
cp $SOURCE_DIR/.zprofile $HOME/
cp $SOURCE_DIR/.zshrc $HOME/

echo "dotfiles copied"

fill_login_secret() {
    echo "Curling contents of url '$1' and appending it to '$secret_filename'"
    curl -fsL -w '\n' "$1" >> $secret_filename
}

filename="$HOME/.secret_links"
if [ -r "$filename" ]; then
    echo "Found secret links file"
    echo "Cleaning $secret_filename"
    rm $secret_filename || :
    touch $secret_filename
    regex='(https?|ftp|file)://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
    while read line; do
        if [[ $line =~ $regex ]]
        then 
            echo "Valid link: $line"
            fill_login_secret $line
        else
            echo "Invalid link: $line"
        fi
    done <$filename
fi
