name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: build-macos
        timeout-minutes: 5
        run: ci/build-macos.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-latest
          path: artifacts/*
          retention-days: 21
          if-no-files-found: error

      - name: Upload Release Binaries
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*